### PR TITLE
Modify version adaptability test

### PR DESCRIPTION
**Pull request by sinhaashish**

### CODE REVIEW

**Comment by balamurugana** [comment]
@sinhaashish its all addressed in https://github.com/minio/direct-csi/pull/465. You could close this PR

**Comment by sinhaashish** [comment]
> @sinhaashish its all addressed in #465. You could close this PR

@balamurugana  there are changes in `interface_test.go` which are not  a part of your PR. IMO this PR is needed

**Comment by balamurugana** [comment]
> > @sinhaashish its all addressed in #465. You could close this PR
> 
> @balamurugana there are changes in `interface_test.go` which are not a part of your PR. IMO this PR is needed

@sinhaashish Have base as #465 and keep specific changes in this PR

**Comment by sinhaashish** [comment]
Closing this as another PR 474 is raised against it

**Pull request closed without merging**
