### PR TITLE
KUBELET_DIR_PATH is required and can be changed as required

### PR DESCRIPTION
**Pull request by sstubbs**
Update the docs so people realise KUBELET_DIR_PATH is required and can be changed. Please see this issue minio/direct-csi#11

### CODE REVIEW

**Comment by sstubbs** [comment]
I'm not entirely sure how to do that to be honest. I did try different variations before I did the PR to change it but it would either not read the environment variable or require the environment variable which is why I did it that way. Perhaps someone with a little more knowledge on this could fix that.

**Comment by harshavardhana** [comment]
> I'm not entirely sure how to do that to be honest. I did try different variations before I did the PR to change it but it would either not read the environment variable or require the environment variable which is why I did it that way. Perhaps someone with a little more knowledge on this could fix that.

Yes in `resources/direct-csi.properties` the `KUBELET_DIR_PATH=` should default to `KUBELET_DIR_PATH=/var/lib/kubelet`

**Comment by sstubbs** [comment]
I'll try it again. When I tried that it was overriding the env variable for some reason. I will create another pr for this if it works.

**Comment by sstubbs** [comment]
Or actually I guess I will just update this branch as it's related to this and change the readme at the same time.

**Comment by harshavardhana** [comment]
Fixed it properly with some doc cleanup https://github.com/minio/direct-csi/pull/18 feel free to close this PR

**Comment by sstubbs** [comment]
ok great thanks

**Pull request closed without merging**
